server.address=0.0.0.0
server.port=8080

mqtt.host=0.0.0.0
mqtt.port=1883
mqtt.allow-anonymous=true
mqtt.enabled=true
mqtt.data-path=./mqtt-data
mqtt.telemetry-topic-prefix=devices
mqtt.devices=40
mqtt.max-payload-bytes=65536
mqtt.history-limit=100
mqtt.sse-queue-capacity=256
spring.jackson.default-property-inclusion=non_null
spring.devtools.restart.enabled=false
